### ISSUE TITLE
Missing cars

### ISSUE THREAD

**Issue by unk2k** [blanzh/carsBase#2]
Hello, I found that Mini Cooper, Mini Cooper S are missing. Could you please check it?

**Comment by blanzh** [comment]
> Hello, I found that Mini Cooper, Mini Cooper S are missing. Could you please check it?

Hi, I think its not a model name. Cooper is styling of Mini Hatch. That's not strictly true, is it? =)

**Comment by unk2k** [comment]
![image](https://user-images.githubusercontent.com/114572/101085559-a4cfb200-35c0-11eb-999b-81dea92eb0ec.png)
I'm sure you right, but by popular car dealers' website, they don't think the same way.
Could you please check cars.com.
