### ISSUE TITLE
Макри/Модели комерческого траснпорта и мото

### ISSUE THREAD

**Issue by Gbutorin** [blanzh/carsBase#3]
Друзья, шикарная работа. А есть ли возможность добавить к базе с авто.ру, марки и модели по коммерческому транспорту и мотоциклам. Так как у авто.ру это отдельными разделами, фактически элементарная газель в список не попадает (так как там по марке ГАЗ, исключительно легковые). буду безмерно благодарен

**Comment by blanzh** [comment]
Коммерческий и мото транспорт базы есть
свяжитесь со мной в телеграме https://t.me/gulpsun

**Comment by vincentpunk** [comment]
Поддерживаю предложение автора. Когда мне нужно было найти коммерческий фургон, я тоже заметил сильное разделение в базах данных. По этой причине искать и собирать информацию о грузовой технике получается намного дольше. В моем случае международный сайт [CheckCar.vin](https://checkcar.vin/pl) очень выручил при проверке истории автомобиля перед покупкой. Было бы отлично увидеть расширение текущей базы, ведь коммерческий сектор сейчас крайне востребован.
